version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  mongo_data:
